// Code generated by cmd/generate-ai-models. DO NOT EDIT.

package ai

func registerGeneratedModels() {
	RegisterModels("anthropic", []Model{
		{
			ID:        "claude-opus-4-6",
			Name:      "Claude Opus 4.6",
			Provider:  "anthropic",
			API:       APIAnthropicMessages,
			MaxTokens: 64000,
		},
		{
			ID:        "claude-sonnet-4-5",
			Name:      "Claude Sonnet 4.5",
			Provider:  "anthropic",
			API:       APIAnthropicMessages,
			MaxTokens: 64000,
		},
	})
	RegisterModels("openai", []Model{
		{
			ID:        "gpt-5",
			Name:      "GPT-5",
			Provider:  "openai",
			API:       APIOpenAIResponses,
			MaxTokens: 128000,
		},
		{
			ID:        "gpt-5-mini",
			Name:      "GPT-5 mini",
			Provider:  "openai",
			API:       APIOpenAIResponses,
			MaxTokens: 128000,
		},
	})
}
