package connector

// DefaultModels contains all default model definitions for each provider.
// This consolidates model definitions that were previously duplicated across provider files.
var DefaultModels = map[string][]ModelInfo{
	"openai": {
		{
			ID:                  "openai/gpt-4o",
			Name:                "GPT 4o",
			Provider:            "openai",
			Description:         "Most capable multimodal model",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			ContextWindow:       128000,
			MaxOutputTokens:     16384,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "openai/gpt-4o-mini",
			Name:                "GPT 4o Mini",
			Provider:            "openai",
			Description:         "Fast and efficient GPT model",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			ContextWindow:       128000,
			MaxOutputTokens:     16384,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "openai/o1",
			Name:                "O1",
			Provider:            "openai",
			Description:         "Advanced reasoning model",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			ContextWindow:       200000,
			MaxOutputTokens:     100000,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "openai/o1-mini",
			Name:                "O1 Mini",
			Provider:            "openai",
			Description:         "Fast reasoning model",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			ContextWindow:       128000,
			MaxOutputTokens:     65536,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "openai/o3-mini",
			Name:                "O3 Mini",
			Provider:            "openai",
			Description:         "Latest reasoning model",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			ContextWindow:       200000,
			MaxOutputTokens:     100000,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "openai/gpt-4-turbo",
			Name:                "GPT 4 Turbo",
			Provider:            "openai",
			Description:         "Previous generation GPT-4 with vision",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			ContextWindow:       128000,
			MaxOutputTokens:     4096,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
	},
	"anthropic": {
		{
			ID:                  "anthropic/claude-sonnet-4-5-20250929",
			Name:                "Claude Sonnet 4.5",
			Provider:            "anthropic",
			Description:         "Latest Claude model with excellent performance",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   false,
			ContextWindow:       200000,
			MaxOutputTokens:     8192,
			AvailableTools:      []string{ToolFunctionCalling},
		},
		{
			ID:                  "anthropic/claude-opus-4-5-20250929",
			Name:                "Claude Opus 4.5",
			Provider:            "anthropic",
			Description:         "Most capable Claude model",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   false,
			ContextWindow:       200000,
			MaxOutputTokens:     8192,
			AvailableTools:      []string{ToolFunctionCalling},
		},
		{
			ID:                  "anthropic/claude-3-5-sonnet-20241022",
			Name:                "Claude 3.5 Sonnet",
			Provider:            "anthropic",
			Description:         "Balanced performance and speed",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   false,
			ContextWindow:       200000,
			MaxOutputTokens:     8192,
			AvailableTools:      []string{ToolFunctionCalling},
		},
		{
			ID:                  "anthropic/claude-3-5-haiku-20241022",
			Name:                "Claude 3.5 Haiku",
			Provider:            "anthropic",
			Description:         "Fast and efficient Claude model",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   false,
			ContextWindow:       200000,
			MaxOutputTokens:     8192,
			AvailableTools:      []string{ToolFunctionCalling},
		},
		{
			ID:                  "anthropic/claude-3-opus-20240229",
			Name:                "Claude 3 Opus",
			Provider:            "anthropic",
			Description:         "Previous generation most capable model",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   false,
			ContextWindow:       200000,
			MaxOutputTokens:     4096,
			AvailableTools:      []string{ToolFunctionCalling},
		},
	},
	"gemini": {
		{
			ID:                  "gemini/gemini-2.5-flash",
			Name:                "Gemini 2.5 Flash",
			Provider:            "gemini",
			Description:         "Fast and efficient model for most tasks",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			ContextWindow:       1000000,
			MaxOutputTokens:     8192,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "gemini/gemini-2.5-pro",
			Name:                "Gemini 2.5 Pro",
			Provider:            "gemini",
			Description:         "Advanced model for complex tasks",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			ContextWindow:       2000000,
			MaxOutputTokens:     8192,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "gemini/gemini-2.0-flash",
			Name:                "Gemini 2.0 Flash",
			Provider:            "gemini",
			Description:         "Previous generation fast model",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			ContextWindow:       1000000,
			MaxOutputTokens:     8192,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "gemini/gemini-2.0-flash-thinking",
			Name:                "Gemini 2.0 Flash Thinking",
			Provider:            "gemini",
			Description:         "Reasoning model with chain-of-thought",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			ContextWindow:       1000000,
			MaxOutputTokens:     8192,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
	},
	"beeper": {
		// MiniMax
		{
			ID:                  "minimax/minimax-m2.1",
			Name:                "MiniMax M2.1",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "minimax/minimax-m2",
			Name:                "MiniMax M2",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		// GLM (Z.AI) - supports reasoning via parameter
		{
			ID:                  "z-ai/glm-4.7",
			Name:                "GLM 4.7",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "z-ai/glm-4.6v",
			Name:                "GLM 4.6V",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		// Kimi (Moonshot)
		{
			ID:                  "moonshotai/kimi-k2-0905",
			Name:                "Kimi K2 (0905)",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "moonshotai/kimi-k2-thinking",
			Name:                "Kimi K2 (Thinking)",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		// Qwen
		{
			ID:                  "qwen/qwen3-235b-a22b-thinking-2507",
			Name:                "Qwen 3 235B (Thinking)",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "qwen/qwen3-235b-a22b",
			Name:                "Qwen 3 235B",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		// Grok (xAI)
		{
			ID:                  "x-ai/grok-4.1-fast",
			Name:                "Grok 4.1 Fast",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		// DeepSeek
		{
			ID:                  "deepseek/deepseek-v3.2",
			Name:                "DeepSeek v3.2",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		// Llama (Meta)
		{
			ID:                  "meta-llama/llama-4-scout",
			Name:                "Llama 4 Scout",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "meta-llama/llama-4-maverick",
			Name:                "Llama 4 Maverick",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		// Gemini (Google) via OpenRouter
		{
			ID:                  "google/gemini-2.5-flash-image",
			Name:                "Nano Banana",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "google/gemini-3-flash-preview",
			Name:                "Gemini 3 Flash",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "google/gemini-3-pro-image-preview",
			Name:                "Nano Banana Pro",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "google/gemini-3-pro-preview",
			Name:                "Gemini 3 Pro",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		// Claude (Anthropic) via OpenRouter
		{
			ID:                  "anthropic/claude-sonnet-4.5",
			Name:                "Claude Sonnet 4.5",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "anthropic/claude-opus-4.5",
			Name:                "Claude Opus 4.5",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "anthropic/claude-haiku-4.5",
			Name:                "Claude Haiku 4.5",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		// GPT (OpenAI) via OpenRouter
		{
			ID:                  "openai/gpt-5-image",
			Name:                "GPT ImageGen 1.5",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: false,
			SupportsReasoning:   false,
			SupportsWebSearch:   false,
			SupportsImageGen:    true,
			AvailableTools:      []string{},
		},
		{
			ID:                  "openai/gpt-5.2",
			Name:                "GPT-5.2",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   true,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "openai/gpt-5-mini",
			Name:                "GPT-5 mini",
			Provider:            "openrouter",
			SupportsVision:      true,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "openai/gpt-oss-20b",
			Name:                "GPT OSS 20B",
			Provider:            "openrouter",
			SupportsVision:      false,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
		{
			ID:                  "openai/gpt-oss-120b",
			Name:                "GPT OSS 120B",
			Provider:            "openrouter",
			SupportsVision:      false,
			SupportsToolCalling: true,
			SupportsReasoning:   false,
			SupportsWebSearch:   true,
			AvailableTools:      []string{ToolWebSearch, ToolFunctionCalling},
		},
	},
}

// GetDefaultModels returns default models for a provider.
// Returns a copy to prevent modification of the original slice.
func GetDefaultModels(provider string) []ModelInfo {
	models, ok := DefaultModels[provider]
	if !ok {
		return nil
	}
	// Return a copy
	result := make([]ModelInfo, len(models))
	copy(result, models)
	return result
}

// GetAllBeeperModels returns all Beeper models for use by generate-models command
func GetAllBeeperModels() []ModelInfo {
	return GetDefaultModels("beeper")
}
