package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"slices"
	"strings"
)

type seedModel struct {
	Provider  string
	ID        string
	Name      string
	API       string
	MaxTokens int
}

func main() {
	models := []seedModel{
		{
			Provider:  "openai",
			ID:        "gpt-5",
			Name:      "GPT-5",
			API:       "APIOpenAIResponses",
			MaxTokens: 128000,
		},
		{
			Provider:  "openai",
			ID:        "gpt-5-mini",
			Name:      "GPT-5 mini",
			API:       "APIOpenAIResponses",
			MaxTokens: 128000,
		},
		{
			Provider:  "anthropic",
			ID:        "claude-sonnet-4-5",
			Name:      "Claude Sonnet 4.5",
			API:       "APIAnthropicMessages",
			MaxTokens: 64000,
		},
		{
			Provider:  "anthropic",
			ID:        "claude-opus-4-6",
			Name:      "Claude Opus 4.6",
			API:       "APIAnthropicMessages",
			MaxTokens: 64000,
		},
	}

	slices.SortFunc(models, func(a, b seedModel) int {
		if cmp := strings.Compare(a.Provider, b.Provider); cmp != 0 {
			return cmp
		}
		return strings.Compare(a.ID, b.ID)
	})

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/generate-ai-models. DO NOT EDIT.\n\n")
	buf.WriteString("package ai\n\n")
	buf.WriteString("func registerGeneratedModels() {\n")

	byProvider := map[string][]seedModel{}
	for _, model := range models {
		byProvider[model.Provider] = append(byProvider[model.Provider], model)
	}
	providers := make([]string, 0, len(byProvider))
	for provider := range byProvider {
		providers = append(providers, provider)
	}
	slices.Sort(providers)

	for _, provider := range providers {
		buf.WriteString(fmt.Sprintf("\tRegisterModels(%q, []Model{\n", provider))
		for _, model := range byProvider[provider] {
			buf.WriteString("\t\t{\n")
			buf.WriteString(fmt.Sprintf("\t\t\tID: %q,\n", model.ID))
			buf.WriteString(fmt.Sprintf("\t\t\tName: %q,\n", model.Name))
			buf.WriteString(fmt.Sprintf("\t\t\tProvider: %q,\n", model.Provider))
			buf.WriteString(fmt.Sprintf("\t\t\tAPI: %s,\n", model.API))
			buf.WriteString(fmt.Sprintf("\t\t\tMaxTokens: %d,\n", model.MaxTokens))
			buf.WriteString("\t\t},\n")
		}
		buf.WriteString("\t})\n")
	}

	buf.WriteString("}\n")

	out, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}

	if err := os.WriteFile("pkg/ai/models_generated.go", out, 0o644); err != nil {
		panic(err)
	}
}
